[package]
name = "max_mult"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
pretty_assertions.workspace = true
rstest.workspace = true

[lints]
workspace = true
